name: deploy

# 新しいコミットがリポジトリにプッシュされるたびにこのワークフローを実行する
on: push

jobs:
  # ジョブキーを設定する。 ジョブ名が指定されていない場合、
  # キーはジョブ名として表示される
  build_deploy:
    # ジョブ名を付ける
    name: Build sapper app

    # 実行するマシンのタイプを設定する
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Build Sapper
        uses: truewebartisans/actions-sapper@master
        with:
          args: "--legacy --basepath expanding-cards"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: __sapper__/export/expanding-cards
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
